"""
ORM entity for a conversation bound to a provider and AI model.

A ``ChatSession`` groups a sequence of
:class:`~src.models.message.Message` rows into one conversation thread,
along with the provider/model selection and any per-session generation
overrides used for that thread. It is the anchor point most other
conversational data hangs off of: messages belong to a session, and
:class:`~src.models.usage_record.UsageRecord` rows optionally reference the
session that produced them.
"""

from __future__ import annotations

import uuid
from typing import TYPE_CHECKING, Any

from sqlalchemy import Boolean, Float, ForeignKey, Integer, String, Text, Uuid, false
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from src.models.base import Base
from src.models.mixins import TimestampMixin

if TYPE_CHECKING:
    from src.models.ai_model import AIModel
    from src.models.message import Message
    from src.models.provider import Provider
    from src.models.usage_record import UsageRecord


class ChatSession(Base, TimestampMixin):
    """
    A single conversation thread with a selected provider and AI model.

    Maps to the ``chat_sessions`` table. ``provider_id`` is denormalized for
    fast filtering (e.g. "all sessions on provider X" without joining
    through ``ai_models``); ``ai_model_id`` is the source of truth for model
    selection. The service layer must ensure
    ``ai_model.provider_id == provider_id`` when creating or updating
    sessions — this invariant is a business rule, not a database
    constraint, because enforcing it with a composite FK would require
    denormalizing ``provider_id`` onto ``ai_models`` in a way that adds
    complexity without a clear database-level benefit.

    Session-level overrides (``system_prompt``, ``temperature_override``,
    ``max_tokens_override``) take precedence over catalog defaults (from
    :class:`~src.models.ai_model_configuration.AIModelConfiguration`) at
    runtime. This lets a single conversation deviate from a model's usual
    defaults (e.g. a more creative temperature for one brainstorming
    session) without altering the model's catalog-wide configuration.

    Columns:
        id: Surrogate primary key, autoincrementing integer. Used for
            internal FKs (e.g. ``messages.session_id``).
        title: Optional human-readable session title, e.g. auto-generated
            from the first message or set by the user. ``String(255)``,
            nullable.
        session_uuid: Public-facing, opaque identifier for this session,
            safe to expose in URLs/APIs without revealing the sequential
            internal ``id``. ``Uuid``, unique, indexed. Generated by the
            application (not a server default) at session-creation time.
        provider_id: Foreign key to ``providers.id``. ``ondelete="CASCADE"``
            — deleting a provider deletes all sessions that used it, since
            a session cannot function without its provider. Indexed.
        ai_model_id: Foreign key to ``ai_models.id``. ``ondelete="CASCADE"``
            — same rationale as ``provider_id``: a session is meaningless
            without the model it was conducted with. Indexed.
        system_prompt: Optional per-session system prompt override, used
            in place of the model's ``system_prompt_template`` default.
            ``Text``, nullable.
        temperature_override: Optional per-session temperature override.
            ``Float``, nullable — ``None`` means "use the model's catalog
            default", not "use temperature 0".
        max_tokens_override: Optional per-session max-tokens override.
            ``Integer``, nullable, same "``None`` = defer to catalog
            default" semantics as ``temperature_override``.
        extra_metadata: Free-form JSON metadata for this session (e.g.
            client-supplied tags). ``JSONB``, nullable. Mapped from the
            database column literally named ``"metadata"`` to the Python
            attribute ``extra_metadata`` because ``metadata`` is a reserved
            attribute name on SQLAlchemy declarative classes (it refers to
            ``Base.metadata``); the first positional argument to
            ``mapped_column`` overrides the column name while the Python
            attribute stays ``extra_metadata``.
        is_archived: Whether the session has been archived (hidden from
            default views but not deleted). ``Boolean``, defaults to
            ``False``, indexed for fast "active sessions" filtering.
        provider: Many-to-one back to :class:`~src.models.provider.Provider`.
            Eagerly loaded (``lazy="selectin"``).
        ai_model: Many-to-one back to :class:`~src.models.ai_model.AIModel`.
            Eagerly loaded (``lazy="selectin"``).
        messages: One-to-many to :class:`~src.models.message.Message`,
            ordered chronologically by ``created_at`` so the collection
            reads naturally as a transcript. ``cascade="all, delete-orphan"``
            — messages have no meaning outside their session.
        usage_records: One-to-many to
            :class:`~src.models.usage_record.UsageRecord`. No delete
            cascade here — usage rows use ``ondelete="SET NULL"`` on their
            FK (see ``UsageRecord.chat_session_id``), so deleting a session
            preserves its usage/billing history rather than deleting it.

    Example:
        >>> import uuid
        >>> session = ChatSession(
        ...     title="Debugging help",
        ...     session_uuid=uuid.uuid4(),
        ...     provider_id=1,
        ...     ai_model_id=1,
        ...     system_prompt="You are a helpful coding assistant.",
        ... )
        >>> session.is_archived
        False
    """

    __tablename__ = "chat_sessions"

    id: Mapped[int] = mapped_column(primary_key=True)

    title: Mapped[str | None] = mapped_column(String(255), nullable=True)

    session_uuid: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True),
        unique=True,
        index=True,
    )

    provider_id: Mapped[int] = mapped_column(
        ForeignKey("providers.id", ondelete="CASCADE"),
        index=True,
    )
    ai_model_id: Mapped[int] = mapped_column(
        ForeignKey("ai_models.id", ondelete="CASCADE"),
        index=True,
    )

    system_prompt: Mapped[str | None] = mapped_column(Text, nullable=True)
    temperature_override: Mapped[float | None] = mapped_column(Float, nullable=True)
    max_tokens_override: Mapped[int | None] = mapped_column(Integer, nullable=True)

    # Python attribute is "extra_metadata" (not "metadata") because
    # "metadata" is reserved by SQLAlchemy's declarative base; the column
    # itself is still named "metadata" in the actual database table.
    extra_metadata: Mapped[dict[str, Any] | None] = mapped_column(
        "metadata",
        JSONB,
        nullable=True,
    )

    is_archived: Mapped[bool] = mapped_column(
        Boolean,
        default=False,
        server_default=false(),
        index=True,
    )

    provider: Mapped[Provider] = relationship(
        "Provider",
        back_populates="chat_sessions",
        lazy="selectin",
    )
    ai_model: Mapped[AIModel] = relationship(
        "AIModel",
        back_populates="chat_sessions",
        lazy="selectin",
    )
    messages: Mapped[list[Message]] = relationship(
        "Message",
        back_populates="chat_session",
        lazy="selectin",
        order_by="Message.created_at",
        cascade="all, delete-orphan",
    )
    usage_records: Mapped[list[UsageRecord]] = relationship(
        "UsageRecord",
        back_populates="chat_session",
        lazy="selectin",
    )

    def __repr__(self) -> str:
        """
        Build a concise, debugger/log-friendly representation of this row.

        Returns:
            A string like ``<ChatSession id=1
            session_uuid=... provider_id=1 ai_model_id=1>`` identifying the
            session and its provider/model selection without including
            potentially large fields like ``system_prompt`` or messages.

        Example:
            >>> import uuid
            >>> s = ChatSession(
            ...     id=1,
            ...     session_uuid=uuid.UUID(int=0),
            ...     provider_id=1,
            ...     ai_model_id=2,
            ... )
            >>> s.__repr__()
            '<ChatSession id=1 session_uuid=00000000-0000-0000-0000-000000000000 provider_id=1 ai_model_id=2>'
        """
        return (
            f"<ChatSession id={self.id} session_uuid={self.session_uuid!s} "
            f"provider_id={self.provider_id} ai_model_id={self.ai_model_id}>"
        )
