"""create providers tables

Revision ID: 3864a2e32a0f
Revises: c8f5e2a31d04
Create Date: 2026-07-27 23:07:00.615086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3864a2e32a0f'
down_revision: Union[str, Sequence[str], None] = 'c8f5e2a31d04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_usage_records_request_id'), 'usage_records', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_records_request_id'), table_name='usage_records')
    # ### end Alembic commands ###
