"""create providers tables

Revision ID: 3864a2e32a0f
Revises: c8f5e2a31d04
Create Date: 2026-07-27 23:07:00.615086

Auto-generated by ``alembic revision --autogenerate`` (note the boilerplate
"### commands auto generated by Alembic ###" markers left in ``upgrade()``/
``downgrade()`` below, and the misleading filename/title inherited from that
autogeneration — despite the name, this migration does not create any
provider *tables*).

What actually happened: ``src/models/usage_record.py`` declares
``request_id`` with both ``index=True`` (a plain, non-unique index) *and* a
separate ``UniqueConstraint`` in ``__table_args__``. The prior migration
(``c8f5e2a31d04``) dropped the plain index when adding the unique
constraint, since a unique constraint already provides an index for lookups
— but that left the ORM model's declared ``index=True`` unsatisfied by the
live schema. Running ``--autogenerate`` therefore detected the missing
plain index and proposed recreating it. The net effect is a (harmless, if
slightly redundant) second index alongside ``uq_usage_records_request_id``
on the same column.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3864a2e32a0f'
down_revision: Union[str, Sequence[str], None] = 'c8f5e2a31d04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Recreate the plain (non-unique) index on ``usage_records.request_id`` so
    the live schema matches the ORM model's ``index=True`` declaration,
    coexisting alongside the ``uq_usage_records_request_id`` unique
    constraint added in the previous migration.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_usage_records_request_id'), 'usage_records', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Drop the plain index added in ``upgrade()``, leaving the unique constraint intact."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_records_request_id'), table_name='usage_records')
    # ### end Alembic commands ###
